Allow grumphp-shim to 2.x version.
axelerant/drupal-quality-checker pull request #27
Opened 2023-12-07 10:46 UTC by rajeshreeputra

2023-12-07 12:28 UTC, hussainweb commented
Thanks, @rajeshreeputra. Is there any reason we should keep support for v1 of the shim? I don't think it has dependencies and so chances of conflicts with other packages is unlikely.

2023-12-08 04:39 UTC, rajeshreeputra commented
> Thanks, @rajeshreeputra. Is there any reason we should keep support for v1 of the shim? I don't think it has dependencies and so chances of conflicts with other packages is unlikely.

Agree Updated to use 2.x version. Thank you!!

2023-12-11 12:22 UTC, hussainweb requested changes
Thanks for your work so far. Please look at my comment.

2023-12-11 12:22 UTC, hussainweb commented on composer.json
> +        }
I am a little concerned with this change and haven't been able to test this. I'll try to do that today. If you can help me understand this better, I can get to it sooner.

My thought is that this probably doesn't help. I am not sure if this configuration takes effect in a package composer.json. There are some settings (such as `repositories`) that can only work in root composer.json. I think this is also one of those settings but I can't find any information about this.

2023-12-11 14:06 UTC, rajeshreeputra commented on composer.json
> +        }
This is saying that these plugins are trusted to make changes in project such as on POST_PACKAGE_INSTALL, POST_PACKAGE_UPDATE etc.
This is mainly useful for development, @hussainweb please provide your opinion on should we keep or not.

2023-12-21 19:14 UTC, hussainweb commented on composer.json
> +        }
Ah, you're right. It does not affect other sites using this package but we still need this for our own development.

2023-12-21 19:15 UTC, merged

2023-12-22 05:00 UTC, rajeshreeputra commented
@hussainweb when can we expect a release.

2023-12-22 10:56 UTC, hussainweb commented
@rajeshreeputra, since this is going to be a breaking release, I will release a new major version. For that, I wanted to change a few more things. Can I get your thoughts on #12 and #21?

2023-12-22 12:25 UTC, rajeshreeputra commented
> @rajeshreeputra, since this is going to be a breaking release, I will release a new major version. For that, I wanted to change a few more things. Can I get your thoughts on #12 and #21? I also created #29 for a generic discussion.

I believe a major version isn't necessary in this case; version 1.4.0 should suffice for this. 
We can proceed with maintenance on the 1.3.x version of phpro/grumphp-shim, addressing any issues that may arise in the 1.x version of phpro/grumphp-shim and resolving them accordingly.

2023-12-22 12:54 UTC, hussainweb commented
Since we are moving to a new major version of a major dependency (GrumPHP), it is a good idea to make a new major release. I don't know what's changed between GrumPHP 1 and 2 but if there are significant changes, then users have to consciously choose to update.