Copy Configuration files
axelerant/drupal-quality-checker pull request #36
Opened 2024-05-07 14:33 UTC by zeshanziya

PR for Issue #7

2024-05-07 14:59 UTC, hussainweb requested changes

2024-05-07 14:59 UTC, hussainweb commented on src/Composer/AxelerantDQCPlugin.php
> +        copy(__DIR__ . '/../../phpstan.neon.dist', $destination . '/phpstan.neon.dist');
As mentioned in the other PR, let's warn and overwrite these files. It sounds like a job for a helper function.

2024-05-07 14:59 UTC, hussainweb commented on src/Composer/AxelerantDQCPlugin.php
> +        $destination = getcwd();
Composer can be run from a subdirectory. I don't think `getcwd` will return the intended path in that case. I believe composer makes a method available to get the project root. It might even be accessible from the `$event` object (which you are not passing here).

2024-05-07 14:59 UTC, hussainweb commented on src/Composer/AxelerantDQCPlugin.php
> +            ScriptEvents::POST_UPDATE_CMD => ['scriptEventAction', 10],
Why not directly set it to `copyFilesToProject`?

2024-05-07 14:59 UTC, hussainweb commented on src/Composer/AxelerantDQCPlugin.php
> +    public function copyFilesToProject(): void
Do you think `copyFilesToProjectRoot` is more descriptive?

2024-05-07 15:11 UTC, zeshanziya commented on src/Composer/AxelerantDQCPlugin.php
> +        copy(__DIR__ . '/../../phpstan.neon.dist', $destination . '/phpstan.neon.dist');
OK will do. will see if we can use Symfony filesystem helper here.

2024-05-07 15:12 UTC, zeshanziya commented on src/Composer/AxelerantDQCPlugin.php
> +        $destination = getcwd();
OK will check and fix

2024-05-07 15:14 UTC, zeshanziya commented on src/Composer/AxelerantDQCPlugin.php
> +            ScriptEvents::POST_UPDATE_CMD => ['scriptEventAction', 10],
I've kept it separate so that if any other actions need to be performed in future development, we can utilize it.

2024-05-07 15:15 UTC, zeshanziya commented on src/Composer/AxelerantDQCPlugin.php
> +    public function copyFilesToProject(): void
Yes, it is. will do the require change

2024-05-07 16:06 UTC, hussainweb commented on src/Composer/AxelerantDQCPlugin.php
> +            ScriptEvents::POST_UPDATE_CMD => ['scriptEventAction', 10],
We can add a new method then. :)

But if you still want to keep a stub method, that's okay. But let's call it something more descriptive.

2024-05-08 03:12 UTC, zeshanziya commented on src/Composer/AxelerantDQCPlugin.php
> +        $destination = getcwd();
I have added a logic to guess the project root. Now it will display an error message if unable to identify project root.

2024-05-08 03:13 UTC, zeshanziya commented on src/Composer/AxelerantDQCPlugin.php
> +            ScriptEvents::POST_UPDATE_CMD => ['scriptEventAction', 10],
Yes makes sense. removed the stub and used `copyFilesToProjectRoot` directly. We can add a stub later when required.

2024-05-08 03:14 UTC, zeshanziya commented on src/Composer/AxelerantDQCPlugin.php
> +        copy(__DIR__ . '/../../phpstan.neon.dist', $destination . '/phpstan.neon.dist');
a warning is displayed if config is already present.

2024-05-08 11:54 UTC, hussainweb commented on src/Composer/AxelerantDQCPlugin.php
> +    }
Is there no composer API to do this? I thought it would be one of the most important things.

2024-05-08 11:54 UTC, hussainweb commented on src/Composer/AxelerantDQCPlugin.php
> +        if ($configPresent) {
This will only write the "overwritten" message if `grumphp.yml.dist` existed. It will silently overwrite the other files. Is that intentional based on our discussion to keep `*.dist` files updated. I think we should still warn that the files have changed.

2024-05-08 11:54 UTC, hussainweb commented on src/Composer/AxelerantDQCPlugin.php
> +    }
I found this block of code in composer: https://github.com/composer/composer/blob/8254811c0776c020932a856e04485152ae12328e/src/Composer/Console/Application.php#L201-L216

It seems to me that we don't need to do anything here, but I am not comfortable with that idea because composer may decide that they don't like `chdir` and break this functionality. We won't even know it's broken. I think they went with `chdir` to keep plugins working but it still seems risky.

Then again, I don't like this idea of guessing the path ourselves either. I'd rather use a API but if composer is relying on `chdir`, then they won't have an API. So, we have to choose between two risky methods.

@zeshanziya, which do you think is better?

2024-05-08 12:49 UTC, zeshanziya commented on src/Composer/AxelerantDQCPlugin.php
> +    }
@hussainweb Yes, I researched but didn't find any API for the same. So, I checked how GrumPHP is identifying the project root to generate `grumphp.yml` file. It uses a similar kind of guessing logic.

So, even if Composer decides to move away from `chdir`, it is more likely that the paths for `vendor` and `bin` directories will change. Therefore, $this->composer->getConfig()->get('bin-dir') will return a path to the project's vendor/bin directory. Thus, we are trying with three paths: `getcwd()`, the `vendor/bin` directory, and the `vendor` directory. I think one of them will always work.

2024-05-08 13:33 UTC, hussainweb commented on src/Composer/AxelerantDQCPlugin.php
> +    }
@zeshanziya, can you add a 2-3 line comment explaining this decision? This is the only thing blocking the merge now.

2024-05-08 13:34 UTC, hussainweb commented on src/Composer/AxelerantDQCPlugin.php
> +        if ($configPresent) {
Yes, the operation continues but we let the user know that the file was overwritten. They shouldn't be surprised later.

2024-05-09 05:04 UTC, zeshanziya commented on src/Composer/AxelerantDQCPlugin.php
> +    }
comment added

2024-05-09 05:04 UTC, zeshanziya commented on src/Composer/AxelerantDQCPlugin.php
> +        if ($configPresent) {
added what configs are overwritten.

2024-05-09 11:47 UTC, hussainweb approved these changes
@zeshanziya, I think that the logic around checking if the file exists is unnecessarily complicated. But we can fix that in another PR. Merging this for now.

2024-05-09 11:47 UTC, hussainweb commented on src/Composer/AxelerantDQCPlugin.php
> +    }
```suggestion
        // Copy each file to the project root.
        $configFiles = ['grumphp.yml.dist', 'phpcs.xml.dist', 'phpmd.xml.dist', 'phpstan.neon.dist'];
        foreach ($configFiles as $filename) {
            $sourcePath = $pluginDirectory . '/' . $filename;
            $destinationPath = $destination . '/' . $filename;
            if (file_exists($destinationPath)) {
                $this->io->write('<fg=yellow>Configuration files (' . implode(', ', $configPresents) . ')  are overwritten. Please watch out for any changes!</fg=yellow>');
            }
            copy($sourcePath, $destinationPath);
        }

        $this->io->write('<fg=green>Configuration files are copied successfully.</fg=green>');
    }
```

2024-05-09 11:48 UTC, merged